networks:
  backend:
    driver: bridge

services:
  
  db:
    container_name: pgdb
    image: postgres:13
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  django:
    container_name: django_app
    build: .
    volumes:
      - .:/app
    ports:
      - "8100:8100"
    depends_on:
      - db
      - redis
    networks:
      - backend
    environment:
      - DATABASE_URL=postgres://django:django_password@db:5432/django
      - REDIS_URL=redis://redis:6379/0

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A countries_project worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - django
    networks:
      - backend

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A countries_project beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - django
    networks:
      - backend

volumes:
  postgres_data:
