# Generated by Django 5.1.6 on 2025-02-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name_official',
            new_name='common_name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='flags_png',
            new_name='flag_png',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='flags_svg',
            new_name='flag_svg',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name_common',
            new_name='official_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='flags_alt',
        ),
        migrations.RemoveField(
            model_name='country',
            name='latlng',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_native',
        ),
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='native_name_common',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='native_name_official',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='continents',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='timezones',
            field=models.CharField(max_length=255),
        ),
    ]
